
  spring:
    config:
      activate:
        on-profile: prod

    datasource:
      url: jdbc:mysql://localhost:3306/likelion_assignment_cr   # ??? MySQL ??????? ??
      username: root                                # ?? MySQL ??? ??
      password: lee1234                             # ?? MySQL ????
      driver-class-name: com.mysql.cj.jdbc.Driver # MySQL ???? ???
